CREATE USER spatial WITH PASSWORD 'spatial' superuser;
GRANT CONNECT ON DATABASE spatial TO spatial;
GRANT USAGE ON SCHEMA public TO spatial;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO spatial;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO spatial;
GRANT ALL PRIVILEGES ON DATABASE spatial TO spatial;